### ISSUE TITLE
Text to Tags processor

### ISSUE THREAD

**Issue by MyNameIsNotPa** [kylepelton/snappy#33]
Given an input of spoken sentences, we need a way to turn the non-carry words (filtering out words like "the", etc) into an array of text tags. These would add to the list of tags in the tagging screen.

**Comment by kylepelton** [comment]
Compiling thoughts for the way we'll implement this in this document: https://docs.google.com/document/d/1oKqPgFlbteQGeCkN8IbKvrjULRFklX2JTIPjMmzvo54/edit
